// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	model "github.com/niktin06sash/MicroserviceProject/UserManagement_service/internal/model"
	service "github.com/niktin06sash/MicroserviceProject/UserManagement_service/internal/service"
)

// MockUserAuthentication is a mock of UserAuthentication interface.
type MockUserAuthentication struct {
	ctrl     *gomock.Controller
	recorder *MockUserAuthenticationMockRecorder
}

// MockUserAuthenticationMockRecorder is the mock recorder for MockUserAuthentication.
type MockUserAuthenticationMockRecorder struct {
	mock *MockUserAuthentication
}

// NewMockUserAuthentication creates a new mock instance.
func NewMockUserAuthentication(ctrl *gomock.Controller) *MockUserAuthentication {
	mock := &MockUserAuthentication{ctrl: ctrl}
	mock.recorder = &MockUserAuthenticationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAuthentication) EXPECT() *MockUserAuthenticationMockRecorder {
	return m.recorder
}

// AuthenticateAndLogin mocks base method.
func (m *MockUserAuthentication) AuthenticateAndLogin(ctx context.Context, user *model.Person) *service.ServiceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateAndLogin", ctx, user)
	ret0, _ := ret[0].(*service.ServiceResponse)
	return ret0
}

// AuthenticateAndLogin indicates an expected call of AuthenticateAndLogin.
func (mr *MockUserAuthenticationMockRecorder) AuthenticateAndLogin(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateAndLogin", reflect.TypeOf((*MockUserAuthentication)(nil).AuthenticateAndLogin), ctx, user)
}

// DeleteAccount mocks base method.
func (m *MockUserAuthentication) DeleteAccount(ctx context.Context, sessionID string, userid uuid.UUID, password string) *service.ServiceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, sessionID, userid, password)
	ret0, _ := ret[0].(*service.ServiceResponse)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockUserAuthenticationMockRecorder) DeleteAccount(ctx, sessionID, userid, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockUserAuthentication)(nil).DeleteAccount), ctx, sessionID, userid, password)
}

// Logout mocks base method.
func (m *MockUserAuthentication) Logout(ctx context.Context, sessionID string) *service.ServiceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(*service.ServiceResponse)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockUserAuthenticationMockRecorder) Logout(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockUserAuthentication)(nil).Logout), ctx, sessionID)
}

// RegistrateAndLogin mocks base method.
func (m *MockUserAuthentication) RegistrateAndLogin(ctx context.Context, user *model.Person) *service.ServiceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegistrateAndLogin", ctx, user)
	ret0, _ := ret[0].(*service.ServiceResponse)
	return ret0
}

// RegistrateAndLogin indicates an expected call of RegistrateAndLogin.
func (mr *MockUserAuthenticationMockRecorder) RegistrateAndLogin(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegistrateAndLogin", reflect.TypeOf((*MockUserAuthentication)(nil).RegistrateAndLogin), ctx, user)
}
