global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:8082']

  - job_name: 'api_service'
    static_configs:
      - targets: ['api_service:8083']