basePath: /
host: localhost:8083
info:
  contact: {}
  description: This is a sample server for managing users and sessions.
  title: API-Gateway
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
