server:
  port: "8082"
redis:  
  host: localhost
  port: 6380        
  password: ""      
  db: 0
database:
  driver: postgres
  host: localhost
  port: 5434
  user: postgres
  password: my_password
  name: users
  sslmode: disable
rabbitmq:
  host: localhost     
  port: 5672                
  name: guest         
  password: guest       
  exchange: user-events-exchange
  routing_key: user.events      
kafka:
  bootstrap_servers: localhost:9092
  retry_backoff_ms: 500
  batch_size: 16384
  acks: "all"  
  topics:
    info_log: "user-info-log-topic"
    error_log: "user-error-log-topic"
    warn_log: "user-warn-log-topic"
session_service:
  grpc_address: "localhost:50052"