server:
  port: "8082"
database:
  driver: postgres
  host: userdb
  port: 5432
  user: postgres
  password: my_password
  name: fc2
  sslmode: disable      
kafka:
  bootstrap_servers: "kafka:9092"
  retry_backoff_ms: 500
  batch_size: 16384
  acks: "all"  
  topics:
    info_log: "user-info-log-topic"
    error_log: "user-error-log-topic"
    warn_log: "user-warn-log-topic"
session_service:
  grpc_address: "session_service:50052"