server:
  port: "8083"
session_service:
  grpc_address: "localhost:50052"
routes:
   /reg: "http://localhost:8082"
   /auth: "http://localhost:8082"
   /del: "http://localhost:8082"
   /logout: "http://localhost:8082"

ssl:
  cert_file: "cert1.pem"
  key_file: "key1.pem"