server:
  port: "8083"
  max_header_bytes: 1048576 
  read_timeout: "10s"
  write_timeout: "10s"
  graceful_shutdown: "10s"
session_service:
  grpc_address: "localhost:50052"
photo_service:
  grpc_address: "localhost:50053"
routes:
   /api/auth/register: "http://localhost:8082/auth/register"
   /api/auth/login: "http://localhost:8082/auth/login"
   /api/users/del: "http://localhost:8082/users/del"
   /api/users/logout: "http://localhost:8082/users/logout"
   /api/me/update: "http://localhost:8082/me/update"
   /api/users: "http://localhost:8082/users"
   /api/me: "http://localhost:8082/me"
kafka:
  bootstrap_servers: localhost:9092
  retry_backoff_ms: 500
  batch_size: 16384
  acks: "all"  
  topics:
    info_log: "api-info-log-topic"
    error_log: "api-error-log-topic"
    warn_log: "api-warn-log-topic"
ssl:
  cert_file: "cert1.pem"
  key_file: "key1.pem"