server:
  port: "8083"
session_service:
  grpc_address: "${SESSION_SERVICE_GRPC_ADDRESS:localhost:50052}"
routes:
   /api/reg: "http://${USER_SERVICE_HOST:localhost}:8082/reg"
   /api/auth: "http://${USER_SERVICE_HOST:localhost}:8082/auth"
   /api/del: "http://${USER_SERVICE_HOST:localhost}:8082/del"
   /api/logout: "http://${USER_SERVICE_HOST:localhost}:8082/logout"
kafka:
  bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  retry_backoff_ms: 500
  batch_size: 16384
  acks: "all"  
  topics:
    info_log: "api-info-log-topic"
    error_log: "api-error-log-topic"
    warn_log: "api-warn-log-topic"
ssl:
  cert_file: "cert1.pem"
  key_file: "key1.pem"