server:
  port: "8083"
session_service:
  grpc_address: "localhost:50052"
routes:
   /api/reg: "http://localhost:8082/reg"
   /api/auth: "http://localhost:8082/auth"
   /api/del: "http://localhost:8082/del"
   /api/logout: "http://localhost:8082/logout"

ssl:
  cert_file: "cert1.pem"
  key_file: "key1.pem"