server:
  port: "8081"      
kafka:
  bootstrap_servers: "localhost:9092"  
  topics:
    user_authenticate: "user-authenticate-topic"
    user_registered: "user-registered-topic"
    user_logged_out: "user-logged-out-topic"
    user_delete: "user-delete-topic"
  group_id: "auth-service-group"  