server:
  port: "50052"
  max_recv_msg_size: 4194304
  max_send_msg_size: 4194304
  graceful_shutdown: "30s"
redis:  
  host: localhost
  port: 6379        
  password: ""      
  db: 0
kafka:
  bootstrap_servers: localhost:9092 
  retry_backoff_ms: 500
  batch_size: 16384
  acks: "all" 
  topics:
    info_log: "session-info-log-topic"
    error_log: "session-error-log-topic"
    warn_log: "session-warn-log-topic"
              