kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "servers_log"
  topics:
    info_log: "info-log-topic"
    error_log: "error-log-topic"
    warn_log: "warn-log-topic"
  enable_auto_commit: false 
  session_timeout: 60000
  heartbeat_interval: 20000    
logger:
  levels:
    info: "info"
    error: "error"
    warn: "warn"
  files:
    info: "internal/logs/info.log"
    error: "internal/logs/error.log"
    warn: "internal/logs/warn.log"
  rotation:
    max_size: 100       
    max_backups: 3         
    max_age: 1             
    compress: true         
  format:          
    time_format: "ISO8601"
